### ISSUE TITLE
Standalone Node-Red Instance

### ISSUE THREAD

**Issue by beccsjb** [victronenergy/node-red-contrib-victron#102]
G'day, your node looks awesome!

Can this node be run on a stand alone instance of Node-Red, not on a GX Device?

It seems to install ok, though when adding a node to a flow, it requests a username and password. I note that the node-red instance i am running is on a Home Assistant Installation. Its fairly normal for Node-Red on Home Assistant to ask for auth, (this is usually my Home Assistant auth details) though it doesnt seem to accept my usual credentials.

![image](https://user-images.githubusercontent.com/43426367/136112346-fcf89796-0cb8-4c85-a55a-6a15147a75ea.png)

The auth prompt only seems to be appearing on the contrib-victron nodes when opening to configure etc.

**Comment by dirkjanfaber** [comment]
Yes, you can run Node-Red standalone instead of on a GX device. Though the support of non-gx installations is limited. The instances where I ran Node-RED locally, I used _dbus over tcp_ (see https://github.com/victronenergy/node-red-contrib-victron#installation-and-usage). But that was never in combination with Home Assistant. Perhaps there is a hint in the logging if you run the node with additional debugging active. 
I would suggest starting Node-RED from the command line with `DEBUG="*" node-red` and keeping an eye on the logging, when the prompt comes up. 
Feel free to add the cause, solution and/or extra information to this issue. I will close the issue in a few days if it becomes inactive.
