### ISSUE TITLE
Grid setpoint out of range

### ISSUE THREAD

**Issue by liquidacid** [victronenergy/node-red-contrib-victron#158]
Hello,

I try to put in a grid setpoint trough Node-Red into Dbus path: /Settings/CGwacs/AcPowerSetPoint but it refuses to accept values over and under +/- 32k ish (16 bit). For the Modbus TCP list i find there are 2 different addresses to put the value to but they address to the same Dbus path.

I would like to be able to add larger numbers to the ESS Control Loop Setpoint but it seems to be impossible. I am currently unable to point what is producing the error since im quite new to node-red. 

The error is: "Error: Number outside range" if i put in 33000 for example but with dbus-spy i can set this value with no issue.

**Comment by dirkjanfaber** [comment]
That issue (see #156) has already been fixed in [this](https://github.com/victronenergy/node-red-contrib-victron/commit/b746e13b9a464e2c7f44675df8116da8d578ac6d) commit. 

If you update to the latest version (1.4.26), it should work. If I am not mistaken, it is part of the latest Venus candidate release.
