### ISSUE TITLE
Improve no devices found text

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#37]
Below screenshot shows what you see after dragging in a node for which there is no matching device on the system. Lots of people will see it; for many it will even be the first thing they see; at least it was like that for me :).

Change the text to `No matching devices found. Pick a different node from the palette.`, or something better.

![image](https://user-images.githubusercontent.com/5200296/54086962-c994e800-434e-11e9-888c-539a35a7f242.png)

**Comment by pkronstrom** [comment]
It might be better to show disabled dropdowns and a message below them instead of a big scary yellow box. Also, specifying the device type in the message is less ambiguous.

Here's a suggestion:

On a new node, the selects are disabled and a red warning text.
![Screenshot 2019-03-12 at 10 29 25](https://user-images.githubusercontent.com/11190027/54185642-3aa0e080-44b2-11e9-97b1-38aa5aadb920.png)

When a previously selected device appears disconnected, the selected values are shown, but not editable. A different warning text is shown.

![Screenshot 2019-03-12 at 10 29 50](https://user-images.githubusercontent.com/11190027/54185714-615f1700-44b2-11e9-9399-d5e5a5925779.png)

Changes [here](https://github.com/victronenergy/node-red-contrib-victron/commit/a62dcfb1785afbb7f933aa4cd8c651260501013a)

**Comment by pkronstrom** [comment]
New style

![Uploading Screenshot 2019-03-12 at 15.01.23.png…]()

**Comment by pkronstrom** [comment]
New style

![Screenshot 2019-03-12 at 15 15 31](https://user-images.githubusercontent.com/11190027/54202886-b3676300-44d9-11e9-86c7-426e5b5dc54a.png)

**Comment by pkronstrom** [comment]
Merged to master
