### ISSUE TITLE
Improve the naming of the device / D-Bus service

### ISSUE THREAD

**Issue by mpvader** [victronenergy/node-red-contrib-victron#38]
Right now we only use the product name in the pulldown (see screenshot). Adding the connection or something could help. Perhaps use a dual line per entry html pulldown, so the connection can be on its own line?

```
root@beaglebone:~# dbus -y  com.victronenergy.temperature.builtin_adc3_di1 /Mgmt/Connection GetValue
value = 'Temperature sensor input 2'
```

![image](https://user-images.githubusercontent.com/5200296/54087006-3b6d3180-434f-11e9-95f0-59fd72da5c0c.png)

![image](https://user-images.githubusercontent.com/5200296/54087024-5b045a00-434f-11e9-89f2-b4dda52fff63.png)

**Comment by pkronstrom** [comment]
It is indeed a challenge to identify services from each other (for a user, that is). Here's a few thoughts on this.

Currently a custom name is shown for each device -- if it is not set, the dropdown label falls back to the product name, which leads to ambiguity in the dropdowns.

I don't really think that showing the dbus service identifier would work here, since the user can't use ttyO0 / ttyO1 / ttyO2 etc. to actually identify similar  devices from each other. If the user actually has several devices of the same type, I would just encourage them to add a custom name from the settings.

Using the /Mgmt/Connection might work as a solution, but is it common for similar devices to use different connection methods? I fear, that for e.g. battery monitors the labels would still stay indistinguishable: BMV-700 (VE.Direct), BMV-700 (VE.Direct), etc. Yet again, setting a CustomName works here.

**Comment by pkronstrom** [comment]
Something like this is should be quite quick to add, if we want to show some service-specific data for the selected service.

![Screenshot 2019-03-12 at 12 03 42](https://user-images.githubusercontent.com/11190027/54191597-e5b79700-44be-11e9-83c7-e487524580e4.png)

**Comment by mpvader** [comment]
Ok;

how are people going to know that setting up a custom name is a solution to their problem?

**Comment by mpvader** [comment]
Hm; cross post. I’ll remove my previous comment.

Ok that will help. But; please do check whats under /Mgmt/Connection for a bmv on a VE.Direct port. Is it really just “VE.Direct”? No port number, nothing?

I’d preft not to show the service name

**Comment by pkronstrom** [comment]
> Ok that will help. But; please do check whats under /Mgmt/Connection for a bmv on a VE.Direct port. Is it

For both simulations and our physical BMV-712: "/Mgmt/Connection": "VE.Direct"

**Comment by mpvader** [comment]
Ok thats too bad.

Then, what about just showing a tip, and only show it if multiple options in the dropdown have the same exact string as a name?

“Tip: go into the menus and set a Custom name to easily distinguish one device from the other.”

**Comment by pkronstrom** [comment]
The following tip is shown if multiple devices with the same name are shown in the edit UI.

![Screenshot 2019-03-12 at 15 01 06](https://user-images.githubusercontent.com/11190027/54202123-04765780-44d8-11e9-85e2-8c942e8443e1.png)

**Comment by mpvader** [comment]
👍

**Comment by pkronstrom** [comment]
Merged to master
