### ISSUE TITLE
Figure out how to hide RPi GPIO nodes from the palette

### ISSUE THREAD

**Issue by pkronstrom** [victronenergy/node-red-contrib-victron#41]
See if there's a way to remove the nodes, since they can't be used

**Comment by pkronstrom** [comment]
AFAIK they can be disabled from the ~/.node-red/.config.json file. This is not exactly a setting file, rather a run-time cache for the settings, so I do not know whether the changes will be persistent.

```
"rpi-gpio": {
     "name": "rpi-gpio",
     "types": [
      "rpi-gpio in",
      "rpi-gpio out",
      "rpi-mouse",
      "rpi-keyboard"
     ],
     "enabled": false,
     "local": false,
     "module": "node-red",
     "file": "/usr/lib/node_modules/node-red/nodes/core/hardware/36-rpi-gpio.js"
    },
```

**Comment by sbender9** [comment]
@mpvader the best way I've found to do this is to just remove the nodes from the filesystem when we build venus. I can make sure that it fails if anything is strange, like the file is not there any more.

I'd rather do this instead of depending on .config.json not getting overwritten or the format changing.

**Comment by mpvader** [comment]
Ok!

**Comment by sbender9** [comment]
In the latest node-red release these are not included by default.
